version: '3.8'

services:
  postgres:
    container_name: nest-clean-pg
    image: postgres
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DATABASE=nest-clean
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres